/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LigaIdRouteImport } from './routes/liga.$id'
import { Route as UtakmicaIdRouteImport } from './routes/utakmica.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LigaIdRoute = LigaIdRouteImport.update({
  id: '/liga/$id',
  path: '/liga/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UtakmicaIdRoute = UtakmicaIdRouteImport.update({
  id: '/utakmica/$id',
  path: '/utakmica/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/liga/$id': typeof LigaIdRoute
  '/utakmica/$id': typeof UtakmicaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/liga/$id': typeof LigaIdRoute
  '/utakmica/$id': typeof UtakmicaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/liga/$id': typeof LigaIdRoute
  '/utakmica/$id': typeof UtakmicaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/liga/$id' | '/utakmica/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/liga/$id' | '/utakmica/$id'
  id: '__root__' | '/' | '/liga/$id' | '/utakmica/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LigaIdRoute: typeof LigaIdRoute
  UtakmicaIdRoute: typeof UtakmicaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liga/$id': {
      id: '/liga/$id'
      path: '/liga/$id'
      fullPath: '/liga/$id'
      preLoaderRoute: typeof LigaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utakmica/$id': {
      id: '/utakmica/$id'
      path: '/utakmica/$id'
      fullPath: '/utakmica/$id'
      preLoaderRoute: typeof UtakmicaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LigaIdRoute: LigaIdRoute,
  UtakmicaIdRoute: UtakmicaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
